#Application URL
url=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login

#Browser Configuration
browser=chrome
edgeDriverPath=C:\\edgedriver_win64\\msedgedriver.exe
# Admin Credentials
username=Admin
password=admin123

# Employee credentials - to be used after AddEmployeeTest creates the account
employeeUsername=ElianaBabirye2
employeePassword=0702959972@Sn

#implicitWait(in seconds)
implicitWait=20

#explicit wait in seconds 
explicitWait=30

#Headless mode (true for Jenkins/CI, false for local testing)
headless=false

claimEventName=Accommodation
claimCurrency=United States Dollar